#!/usr/bin/env python3
"""Single-project UI checks. Uses disposable browser pages and temporary project files."""
from pathlib import Path
from tempfile import TemporaryDirectory
from http.server import ThreadingHTTPServer
import json, os, re, shutil, sys, threading, time, http.client
from playwright.sync_api import sync_playwright, expect
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT))
from server import ProjectStore,make_handler,parse_project
OUT=ROOT/'test-results';OUT.mkdir(exist_ok=True)
HTML=(ROOT/'dist/research-flow.html').read_text()
CLASSIC=json.loads((ROOT/'tests/fixtures/classic-project.json').read_text())
HTML=re.sub(r'(<script id="initial-project" type="application/json">).*?(</script>)',lambda m:m[1]+json.dumps(CLASSIC)+m[2],HTML,flags=re.S)
CHECKS=[]; ERRORS=[]
def check(value,label):
    if not value: raise AssertionError(label)
    CHECKS.append(label);print('PASS',label,flush=True)
def open_page(browser,html=HTML,width=1600,height=1000):
    pg=browser.new_page(viewport={'width':width,'height':height},accept_downloads=True)
    pg.set_default_timeout(5000)
    pg.on('pageerror',lambda e:ERRORS.append(str(e)))
    pg.set_content(html,wait_until='load')
    expect(pg.locator('#save-button')).to_be_enabled()
    return pg
def snapshot(pg):
    pg.locator('#more-menu summary').click()
    with pg.expect_download() as dl: pg.locator('[data-action="export-json"]').click()
    return json.loads(Path(dl.value.path()).read_text())
def select(pg,task):
    pg.locator(f'.task-node[data-id="{task}"]').click()
    expect(pg.locator('#inspector')).to_be_visible()
def overview(pg):
    if pg.locator('#inspector').is_visible(): pg.locator('[data-action="close-inspector"]').click()
    pg.locator('#overview-button').click()
def drag(pg,src,dst):
    a=pg.locator(src).bounding_box();b=pg.locator(dst).bounding_box()
    pg.mouse.move(a['x']+a['width']/2,a['y']+a['height']/2);pg.mouse.down()
    pg.mouse.move(b['x']+b['width']/2,b['y']+b['height']/2,steps=10);pg.mouse.up()
def task(doc,id):return next(t for t in doc['tasks'] if t['id']==id)
def click_edge(pg,key):
    # Pick the middle of the actual rendered curve, not its off-screen bounding box.
    pg.locator(f'[data-edge="{key}"]').evaluate('el => el.focus()')
    pg.keyboard.press('Enter')
    expect(pg.locator('#connection-form')).to_be_visible()

def run():
 with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium'),headless=True,args=['--no-sandbox'])
    pg=open_page(browser);requests=[];pg.on('request',lambda r:requests.append(r.url))
    base=snapshot(pg)
    check(pg.locator('.task-node').count()==8 and pg.locator('.edge-hit').count()==9,'overview contains the original eight steps and nine connections')
    check(not pg.locator('#inspector').is_visible() and not pg.locator('#focus-button').is_visible(),'fresh project opens without a preselected step or empty inspector')
    check(pg.locator('.sidebar,input[type=file],[data-action="open-file"],[data-action="new-project"],[data-action="source"],#ready-list,#progress-fill,#brand-dialog').count()==0,'project switching, import, source editor, dashboard, ready prompts and branding settings are removed from the DOM')
    check(not any(s in pg.locator('body').inner_text() for s in ['Ready next','Ready to start','Comes next','Upcoming Ready']),'workflow contains no suggested-next-step messages')
    check(pg.locator('#minimap-wrap').is_visible(),'global minimap is visible on startup')
    check(pg.locator('.brand-logo [data-logo-dots] circle').count()==64 and pg.locator('.brand-logo #rf-logo-arrow').count()==1 and pg.locator('link[rel=icon]').count()==2,'original inline SVG dot artwork, fixed arrow and light/dark favicons are retained')
    pg.screenshot(path=str(OUT/'essential-overview.png'))
    select(pg,'design');pg.locator('#focus-button').click()
    check(pg.locator('.task-node:visible').count()==4 and pg.locator('.edge-hit').count()==3,'Focus keeps the selected step and its immediate incoming/outgoing steps')
    check('4 of 8' in pg.locator('#view-context').inner_text(),'Focus identifies that only part of the project is shown')
    check(snapshot(pg)==base,'Focus is a view operation and does not change project data or layout')
    pg.screenshot(path=str(OUT/'essential-focus.png'))
    pg.locator('#overview-button').click()
    check(pg.locator('.task-node:visible').count()==8,'Overview restores the complete workflow')
    pg.locator('[data-field=title]').fill('Study design & validation')
    pg.locator('[data-field=goal]').fill('Choose a reproducible and testable analysis.')
    pg.locator('[data-field=status]').select_option('blocked')
    pg.locator('#resources-tab').click()
    pg.locator('[data-field=notes]').fill('An assumption: use biological replicates.\nDo not invent missing data.')
    pg.locator('[data-field=inputs]').fill('data/counts.tsv\nnotes/review.md')
    pg.locator('[data-field=outputs]').fill('reports/plan.md\nanalysis/design.py')
    pg.locator('#plan-tab').click();pg.locator('#resources-tab').click()
    edited=snapshot(pg)
    check(task(edited,'design')['title']=='Study design & validation' and task(edited,'design')['status']=='blocked','title and status edits update the underlying project')
    check(task(edited,'design')['inputs']==['data/counts.tsv','notes/review.md'] and task(edited,'design')['notes'].startswith('An assumption:'),'notes and multiline file references survive tab switching')
    check(task(edited,'analysis').get('agent_instructions')==task(base,'analysis').get('agent_instructions'),'hidden existing handoff data is preserved')
    pg.locator('#resources-tab').focus();pg.keyboard.press('ArrowLeft')
    check(pg.locator('#plan-panel').is_visible(),'Plan/Notes tabs support arrow-key navigation')
    pg.locator('[data-action="close-inspector"]').click();pg.locator('#details-button').click()
    check(pg.locator('[data-field="title"]').input_value()=='Study design & validation','Details can be closed and reopened without losing edits')
    with pg.expect_download() as dl:pg.locator('#save-button').click()
    saved=Path(dl.value.path()).read_text()
    reopen=open_page(browser,saved)
    check(snapshot(reopen)==edited,'Save copy downloads a standalone HTML that reopens with all current edits')
    with reopen.expect_download() as dl:reopen.locator('#save-button').click()
    second=Path(dl.value.path()).read_text()
    again=open_page(browser,second)
    check(snapshot(again)==edited,'a saved copy can itself be saved and reopened again')
    reopen.close();again.close();pg.close()

    pg=open_page(browser)
    before=snapshot(pg);node=pg.locator('.task-node[data-id=data_qc]');b=node.bounding_box()
    pg.mouse.move(b['x']+70,b['y']+50);pg.mouse.down();pg.mouse.move(b['x']+125,b['y']+82,steps=8);pg.mouse.up()
    after=snapshot(pg)
    check(after['layout']['positions']['data_qc']!=before['layout']['positions']['data_qc'],'dragging a card changes its saved position')
    check(not pg.locator('#inspector').is_visible(),'dragging does not open the inspector or resize the canvas mid-drag')
    pg.locator('#undo-button').click();check(snapshot(pg)==before,'Undo restores a dragged card and all project data')
    pg.locator('#redo-button').click();check(snapshot(pg)==after,'Redo reapplies the card movement')
    pg.locator('#undo-button').click();overview(pg)
    node=pg.locator('.task-node[data-id=data_qc]');r=node.bounding_box()
    pg.mouse.move(r['x']+65,r['y']+50);pg.mouse.down();pg.mouse.move(r['x']+90,r['y']+80,steps=4)
    pg.locator('#canvas').dispatch_event('pointercancel',{'pointerId':1,'clientX':r['x']+90,'clientY':r['y']+80})
    pg.mouse.up()
    check(snapshot(pg)==before,'cancelled drag restores the prior position without a partial edit')
    drag(pg,'.port.out[data-id=data_qc]','.port.in[data-id=analysis]')
    connected=snapshot(pg)
    check('data_qc' in task(connected,'analysis')['depends_on'],'dragging output to input creates a real dependency')
    pg.locator('#undo-button').click();check(snapshot(pg)==before,'Undo reverses a newly drawn connection')
    pg.locator('.port.out[data-id=literature]').click();pg.locator('.port.in[data-id=analysis]').click()
    check('literature' in task(snapshot(pg),'analysis')['depends_on'],'click-output then click-input connects without dragging')
    pg.locator('#undo-button').click()
    pg.locator('.port.out[data-id=literature]').focus();pg.keyboard.press('Enter');pg.locator('.port.in[data-id=analysis]').focus();pg.keyboard.press('Space')
    check('literature' in task(snapshot(pg),'analysis')['depends_on'],'connection handles support keyboard-only activation')
    pg.locator('#undo-button').click();old=snapshot(pg)
    # A backward link must not corrupt a valid DAG.
    pg.locator('.port.out[data-id=synthesis]').focus();pg.keyboard.press('Enter');pg.locator('.port.in[data-id=question]').focus();pg.keyboard.press('Enter')
    check(pg.locator('.toast.error').count()>0 and snapshot(pg)==old,'cycle-producing connections are rejected without modifying the plan')
    pg.locator('.port.out[data-id=literature]').focus();pg.keyboard.press('Enter');pg.keyboard.press('Escape')
    check(pg.locator('#connection-prompt').is_hidden(),'Escape cancels a pending connection')
    select(pg,'design');pg.locator('#add-dependency').select_option('question')
    check('question' in task(snapshot(pg),'design')['depends_on'],'inspector provides a non-dragging dependency editor')
    pg.locator('.dependency-row [data-action=remove-dependency][data-source=question][data-target=design]').click()
    check('question' not in task(snapshot(pg),'design')['depends_on'],'incoming connections can be removed directly in the inspector')
    pg.locator('.dependency-row [data-action=remove-dependency][data-source=design][data-target=analysis]').click()
    check('design' not in task(snapshot(pg),'analysis')['depends_on'],'outgoing connections can also be removed in the inspector')
    pg.locator('#undo-button').click();overview(pg)
    point=pg.locator('[data-edge="analysis|validation"]').evaluate('el=>{const p=el.getPointAtLength(el.getTotalLength()/2);const q=new DOMPoint(p.x,p.y).matrixTransform(el.getScreenCTM());return {x:q.x,y:q.y}}')
    pg.mouse.click(point['x'],point['y']);expect(pg.locator('#connection-form')).to_be_visible()
    check(True,'a mouse click on a curved arrow opens its connection editor')
    pg.locator('#connection-source').select_option('design');pg.locator('#connection-form button[type=submit]').click()
    check(task(snapshot(pg),'validation')['depends_on']==['design'],'connection inspector can change an endpoint')
    pg.locator('#undo-button').click();click_edge(pg,'question|literature');pg.locator('[data-action=reverse-edge]').click()
    check('literature' in task(snapshot(pg),'question')['depends_on'] and not task(snapshot(pg),'literature')['depends_on'],'Reverse changes direction when the resulting graph is valid')
    pg.locator('#undo-button').click();click_edge(pg,'question|literature')
    pg.locator('#connection-source').select_option('synthesis');pg.locator('#connection-form button[type=submit]').click()
    check(pg.locator('#connection-error').inner_text()!='' and snapshot(pg)==before,'invalid endpoint changes show an inline error and keep the original connection')
    pg.keyboard.press('Escape');overview(pg);click_edge(pg,'analysis|validation');pg.keyboard.press('Tab')
    pg.locator('[data-action=delete-edge]').click()
    check('analysis' not in task(snapshot(pg),'validation')['depends_on'],'selected connection can be deleted')
    pg.locator('#undo-button').click();check(snapshot(pg)==before,'Undo restores a deleted connection')
    pg.close()

    pg=open_page(browser)
    pg.locator('#add-button').click();select(pg,'step_1');pg.locator('[data-field=title]').fill('Validate inputs')
    added=snapshot(pg);newid=next(t['id'] for t in added['tasks'] if t['title']=='Validate inputs')
    check(len(added['tasks'])==9 and not task(added,newid)['depends_on'],'Add step creates an independent editable step without requiring a technical ID')
    pg.locator('[data-action=add-after]').click();select(pg,'step_2');pg.locator('[data-field=title]').fill('Validate inputs')
    added=snapshot(pg);child=added['tasks'][-1]
    check(child['id']!=newid and child['depends_on']==[newid],'Add connected step sets its dependency and generates a unique stable ID')
    pg.on('dialog',lambda d:d.accept())
    pg.locator('[data-action=delete-task]').click();pg.locator('#confirm-delete-step').click();check(len(snapshot(pg)['tasks'])==9,'Delete step removes only the selected step')
    pg.locator('#undo-button').click();check(len(snapshot(pg)['tasks'])==10,'Undo restores a deleted step')
    overview(pg);pg.locator('#more-menu summary').click();pg.locator('[data-action=view-list]').click()
    check(pg.locator('#list-view tbody tr').count()==10,'optional step list retains an editable overview')
    pg.locator(f'[data-table-status={newid}]').select_option('done');check(task(snapshot(pg),newid)['status']=='done','status can be changed inline in the optional list')
    pg.locator('#overview-button').click();pg.locator('#more-menu summary').click();pg.locator('[data-action=toggle-map]').click()
    check(pg.locator('#minimap-wrap').is_hidden(),'global minimap can still be hidden')
    pg.locator('#more-menu summary').click();pg.locator('[data-action=toggle-map]').click()
    check(pg.locator('#minimap-wrap').is_visible(),'global minimap can be restored')
    prev=pg.locator('#world').get_attribute('style');pg.locator('#minimap-wrap').click(position={'x':35,'y':50})
    check(prev!=pg.locator('#world').get_attribute('style'),'minimap click navigates the canvas')
    pg.locator('#more-menu summary').click();pg.locator('[data-action=layout]').click()
    arranged=snapshot(pg);check(arranged['layout']['positions']!=added['layout']['positions'],'Arrange steps remains available in More options')
    pg.locator('#project-title').fill('Our project');pg.locator('#project-title').press('Enter')
    check(snapshot(pg)['project']['name']=='Our project' and pg.locator('#project-title').evaluate('el=>getComputedStyle(el).textTransform')=='uppercase','uppercase title styling does not alter the saved project name')
    before=snapshot(pg);pg.keyboard.press('o');pg.locator('.task-node').first.focus();pg.keyboard.press('ArrowRight')
    after=snapshot(pg);check(after['layout']['positions']['question']['x']==before['layout']['positions']['question']['x']+10,'keyboard arrow keys can move a focused step')
    pg.close()

    # Unrecognized metadata must survive editing / exporting.
    raw=re.search(r'<script id="initial-project" type="application/json">(.*?)</script>',HTML,re.S).group(1)
    custom=json.loads(raw);custom['project']['owner']='Example';custom['tasks'][0]['evidence']={'checked':False,'refs':['X']}
    customhtml=HTML.replace(raw,json.dumps(custom).replace('<','\\u003c'))
    pg=open_page(browser,customhtml);select(pg,'question');pg.locator('[data-field=goal]').fill('<script>bad()</script>')
    doc=snapshot(pg);check(doc['project']['owner']=='Example' and doc['tasks'][0]['evidence']==custom['tasks'][0]['evidence'],'unknown project/task metadata is preserved')
    check(pg.locator('#nodes script').count()==0,'user-supplied markup is escaped, not executed')
    pg.close()
    custom['tasks']=[];custom['layout']['positions']={}
    pg=open_page(browser,HTML.replace(raw,json.dumps(custom)))
    check(pg.locator('#empty-state').is_visible() and pg.locator('#inspector').is_hidden(),'empty workflow has one useful Add step action instead of dashboard placeholders')
    pg.close()

    for width,height in [(1920,1080),(1600,1000),(1440,900),(1280,800),(1024,768),(820,1180),(700,900),(390,844),(320,640)]:
      pg=open_page(browser,width=width,height=height)
      check(pg.evaluate('document.documentElement.scrollWidth <= innerWidth'),'no horizontal document overflow at '+str(width)+'px')
      pg.screenshot(path=str(OUT/f'essential-{width}.png'))
      # Open a visible step. On medium widths choose the center stage.
      target='question' if width<=700 else 'design'
      select(pg,target)
      bound=pg.locator('#inspector').bounding_box()
      check(bound['x']>=0 and bound['x']+bound['width']<=width+1 and bound['y']+bound['height']<=height+1,'selection details stay in viewport at '+str(width)+'px')
      if width in [390,1280]:pg.screenshot(path=str(OUT/f'essential-details-{width}.png'))
      pg.locator('[data-action=close-inspector]').click()
      pg.locator('#more-menu summary').click()
      menu=pg.locator('.menu-panel').bounding_box()
      check(menu['x']>=0 and menu['x']+menu['width']<=width+1,'More menu stays in viewport at '+str(width)+'px')
      pg.close()
    offline=browser.new_page();network=[];offline.on('request',lambda r:network.append(r.url))
    offline.set_content(HTML,wait_until='load');expect(offline.locator('.task-node')).to_have_count(8)
    check(not [url for url in network if url.startswith(('https:','http:'))],'standalone performs no external runtime, font, logo or analytics requests')
    offline.close()
    check(not ERRORS,'no uncaught JavaScript errors in browser interactions')

    with TemporaryDirectory() as td:
      projectfile=Path(td)/'project.yaml';projectfile.write_text(json.dumps(CLASSIC))
      store=ProjectStore(projectfile);httpd=ThreadingHTTPServer(('127.0.0.1',0),make_handler(store))
      thread=threading.Thread(target=httpd.serve_forever,daemon=True);thread.start()
      pg=browser.new_page(viewport={'width':1440,'height':900},accept_downloads=True);pg.set_default_timeout(10000)
      pg.on('pageerror',lambda e:ERRORS.append(str(e)))
      # The environment blocks browser navigation to localhost. Bridge only the
      # test fetch transport; all API validation, revisions and disk IO remain real.
      def bridge(url,options=None):
        options=options or {};assert url.startswith('/api/')
        conn=http.client.HTTPConnection('127.0.0.1',httpd.server_port)
        conn.request(options.get('method') or 'GET',url,body=options.get('body'),headers=options.get('headers') or {})
        r=conn.getresponse();result={'status':r.status,'text':r.read().decode()};conn.close();return result
      pg.expose_function('__test_http',bridge)
      bridge_js="""window.RESEARCH_FLOW_PREVIEW = false;
window.fetch = async (url, options = {}) => {
 const data = await window.__test_http(url, {method:options.method,headers:options.headers,body:options.body});
 return new Response(data.text, {status:data.status,headers:{'Content-Type':'application/json'}});
};"""
      pg.set_content(HTML.replace('window.RESEARCH_FLOW_PREVIEW = true;',bridge_js),wait_until='load')
      expect(pg.locator('#save-state')).to_have_text('Saved')
      check(pg.locator('#save-button').is_disabled(),'local app does not offer a redundant save when unchanged')
      select(pg,'data_qc');pg.locator('[data-field=title]').fill('QC saved to disk');pg.locator('#save-button').click()
      expect(pg.locator('#save-state')).to_have_text('Saved')
      check(task(parse_project(projectfile.read_text()),'data_qc')['title']=='QC saved to disk','Save writes edited project data to the actual YAML file')
      check(any((Path(td)/'.research-flow').rglob('*')),'local save retains backend backup storage')
      # External clean reload of current project, not import/switching.
      doc=parse_project(projectfile.read_text());doc['project']['name']='External change';projectfile.write_text(json.dumps(doc))
      expect(pg.locator('#project-title')).to_have_value('External change',timeout=10000)
      check(True,'clean external edits refresh the same project automatically')
      pg.locator('[data-field=goal]').fill('My unsaved browser edit')
      doc=parse_project(projectfile.read_text());doc['project']['description']='A concurrent disk edit';projectfile.write_text(json.dumps(doc))
      expect(pg.locator('#file-alert')).to_be_visible(timeout=10000)
      check(pg.locator('#save-button').is_disabled() and pg.locator('[data-field=goal]').input_value()=='My unsaved browser edit','external conflict preserves the unsaved draft and prevents overwrite')
      pg.on('dialog',lambda d:d.accept());pg.locator('[data-action=reload]').click()
      expect(pg.locator('#file-alert')).to_be_hidden()
      check(pg.locator('#save-state').inner_text()=='Saved','explicit reload resolves a conflict for the current project only')
      pg.close();httpd.shutdown();httpd.server_close()
    check(not ERRORS,'no browser errors after real local-server save and conflict checks')
    browser.close()
    (OUT/'essential-checks.json').write_text(json.dumps({'count':len(CHECKS),'checks':CHECKS,'errors':ERRORS},indent=2))
    print('ALL',len(CHECKS),'CHECKS PASSED',flush=True)
if __name__=='__main__':run()
